### ISSUE TITLE
Test tools/test_utils.py test_random_token sometimes fails apprently randomly

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#286]
this https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/tests/tools/test_utils.py#L51

fails sometimes, as shown here: https://github.com/italia/eudi-wallet-it-python/actions/runs/11464697451/job/31901483660#step:9:90

needs further analysis

**Comment by Zicchio** [comment]
The bug is in the test.

There are cases when the random token `'00'` is created and is perfectly valid, it represent the integer zero, but the assertion require that it is non-zero
https://github.com/italia/eudi-wallet-it-python/blob/2eb59f04514c0110166a92f2a1ce3e902e245950/pyeudiw/tests/tools/test_utils.py#L81
in general, that assertion is not a valid check as the method `int(…)` raises an exception when it fails.

Will follow up with fixing pull request
